# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/map_reduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/map_reduce.proto\x12\x0f\x62\x61\x63kup_protocol\x1a\x1bgoogle/protobuf/empty.proto\"u\n\x0cNotifyMapper\x12\x10\n\x08my_index\x18\x01 \x01(\x05\x12\x13\n\x0bnum_reducer\x18\x02 \x01(\x05\x12\x13\n\x0binput_paths\x18\x03 \x03(\t\x12\t\n\x01k\x18\x04 \x01(\x05\x12\x0e\n\x06xcoord\x18\x05 \x03(\x02\x12\x0e\n\x06ycoord\x18\x06 \x03(\x02\"Q\n\rNotifyReducer\x12\x10\n\x08my_index\x18\x01 \x01(\x05\x12\x12\n\nnum_mapper\x18\x02 \x01(\x05\x12\x1a\n\x12intermediate_paths\x18\x03 \x03(\t\"O\n\nFormatFile\x12)\n\x08response\x18\x01 \x01(\x0e\x32\x17.backup_protocol.Status\x12\x16\n\x0eoutfinal_paths\x18\x02 \x03(\t*!\n\x06Status\x12\n\n\x06MAPPER\x10\x00\x12\x0b\n\x07REDUCER\x10\x01\x32M\n\x06Master\x12\x43\n\x0cNotifyMaster\x12\x1b.backup_protocol.FormatFile\x1a\x16.google.protobuf.Empty2N\n\x06Mapper\x12\x44\n\x0bStartMapper\x12\x1d.backup_protocol.NotifyMapper\x1a\x16.google.protobuf.Empty2Q\n\x07Reducer\x12\x46\n\x0cStartReducer\x12\x1e.backup_protocol.NotifyReducer\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.map_reduce_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=355
  _STATUS._serialized_end=388
  _NOTIFYMAPPER._serialized_start=72
  _NOTIFYMAPPER._serialized_end=189
  _NOTIFYREDUCER._serialized_start=191
  _NOTIFYREDUCER._serialized_end=272
  _FORMATFILE._serialized_start=274
  _FORMATFILE._serialized_end=353
  _MASTER._serialized_start=390
  _MASTER._serialized_end=467
  _MAPPER._serialized_start=469
  _MAPPER._serialized_end=547
  _REDUCER._serialized_start=549
  _REDUCER._serialized_end=630
# @@protoc_insertion_point(module_scope)
